spring:
  #  datasource:
  #    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  #    username: sa
  #    password:
  #    initialization-mode: always
  #    driverClassName: org.h2.Driver
  #  h2:
  #    console:
  #      enabled: true
  #  jpa:
  #    hibernate:
  #    ddl-auto: update
  #    dialect: org.hibernate.dialect.H2Dialect
  #    show-sql: true
  #    defer-datasource-initialization: true
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/testback"
    username: "root"
    password:
    initialize: true
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
    generate-ddl: true
    ddl-auto: update
    dialect: com.mysql.jdbc.Driver
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  springdoc:
    api-docs:
      path=/api-docs: